---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-arm
  labels:
    name: debug-arm
spec:
  selector:
    matchLabels:
      name: debug-arm
  template:
    metadata:
      labels:
        name: debug-arm
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: arm
          image: jhansen/k8s-debug-pod:0.1.0
          command: ["/bin/sh", "-c", "while true; do date && curl -v -qs https://management.azure.com > /dev/null && sleep ${POD_SLEEP_SECS}; done "]
          env:
            - name: POD_SLEEP_SECS
              value: "30"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
        - name: aad
          image: jhansen/k8s-debug-pod:0.1.0
          command: ["/bin/sh", "-c", "while true; do date && curl -v -qs https://login.microsoftonline.com > /dev/null && sleep ${POD_SLEEP_SECS}; done "]
          env:
            - name: POD_SLEEP_SECS
              value: "30"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 30
